/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics",
  "tagline": "Learn robotics through ROS 2, simulation, and hands-on exercises — build, simulate, and deploy real robots with step-by-step labs, practical projects, and clear examples.",
  "favicon": "img/favicon.ico",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "url": "https://Muhammad-Shahr0z.github.io",
  "baseUrl": "/Hackathon-2025-Robotics-ai-Book1/",
  "organizationName": "Muhammad-Shahr0z",
  "projectName": "Hackathon-2025-Robotics-ai-Book1",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "docs",
          "sidebarPath": "./sidebars.ts",
          "showLastUpdateTime": false,
          "editCurrentVersion": false
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "logo": {
        "alt": "Robotics AI",
        "src": "img/logo.png",
        "href": "/",
        "target": "_self"
      },
      "title": "Humanoid Robotic AI",
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Book Chapters"
        },
        {
          "href": "https://github.com/Muhammad-Shahr0z/Hackathon-2025-Robotics-ai-Book1",
          "label": "GitHub",
          "position": "right"
        },
        {
          "type": "custom-authButton",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learning Modules",
          "items": [
            {
              "label": "Module 1: ROS 2 Fundamentals",
              "to": "/docs/module-1/"
            },
            {
              "label": "Module 2: Sensors & Perception",
              "to": "/docs/module-2/"
            },
            {
              "label": "Module 3: Navigation & SLAM",
              "to": "/docs/module-3/"
            },
            {
              "label": "Module 4: Manipulation",
              "to": "/docs/module-4/"
            },
            {
              "label": "Module 5: Advanced Topics",
              "to": "/docs/module-5/"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub Repository",
              "href": "https://github.com/Muhammad-Shahr0z/Hackathon-2025-Robotics-ai-Book1"
            },
            {
              "label": "Report Issues",
              "href": "https://github.com/Muhammad-Shahr0z/Hackathon-2025-Robotics-ai-Book1/issues"
            },
            {
              "label": "Discussions",
              "href": "https://github.com/Muhammad-Shahr0z/Hackathon-2025-Robotics-ai-Book1/discussions"
            },
            {
              "label": "ROS Discourse",
              "href": "https://discourse.ros.org/"
            },
            {
              "label": "ROS Answers",
              "href": "https://answers.ros.org/"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "ROS 2 Documentation",
              "href": "https://docs.ros.org/en/humble/"
            },
            {
              "label": "Gazebo Simulator",
              "href": "https://gazebosim.org/"
            },
            {
              "label": "MoveIt 2",
              "href": "https://moveit.ros.org/"
            },
            {
              "label": "Nav2 Documentation",
              "href": "https://navigation.ros.org/"
            },
            {
              "label": "Contributing Guide",
              "href": "https://github.com/Muhammad-Shahr0z/Hackathon-2025-Robotics-ai-Book1/blob/main/CONTRIBUTING.md"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Physical AI & Humanoid Robotics Textbook. Built with ❤️ by Muhammad Shahroz."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": []
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
